x-common:
  database: &db-environment
    MYSQL_PASSWORD: &db-password ${MYSQL_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  panel:
    &panel-environment # This URL should be the URL that your reverse proxy routes to the panel server
    APP_URL: 'http://panel.codinglab.gg'
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: 'Europe/Paris'
    APP_SERVICE_AUTHOR: 'noreply@codinglab.gg'
    TRUSTED_PROXIES: '*' # Set this to your proxy IP
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: 'neolectron@codinglab.io'
  mail: &mail-environment
    MAIL_FROM: 'noreply@codinglab.gg'
    MAIL_DRIVER: 'smtp'
    MAIL_HOST: 'mail'
    MAIL_PORT: '1025'
    MAIL_USERNAME: ''
    MAIL_PASSWORD: ''
    MAIL_ENCRYPTION: 'true'

# ------------------------------------------------------------------------------------------
services:
  database:
    image: mariadb:10.5
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      <<: *db-environment
      MYSQL_DATABASE: 'panel'
      MYSQL_USER: 'pterodactyl'
    networks:
      - dokploy-network

  cache:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - dokploy-network
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    depends_on:
      - database
      - cache
    volumes:
      - '../files/pterodactyl/var/:/app/var/'
      - '../files/pterodactyl/nginx/:/etc/nginx/http.d/'
      - '../files/pterodactyl/certs/:/etc/letsencrypt/'
      - '../files/pterodactyl/logs/:/app/storage/logs'
    networks:
      - dokploy-network
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: 'production'
      APP_ENVIRONMENT_ONLY: 'false'
      CACHE_DRIVER: 'redis'
      SESSION_DRIVER: 'redis'
      QUEUE_DRIVER: 'redis'
      REDIS_HOST: 'cache'
      DB_HOST: 'database'
      DB_PORT: '3306'

volumes:
  db-data:

networks:
  dokploy-network:
    external: true
